name: studiffy
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.4
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  mime: ^2.0.0
  http_parser: ^4.0.2
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  material_symbols_icons: ^4.2815.0
  no_screenshot: ^0.3.1
  collection: ^1.18.0
  loader_overlay: ^4.0.4+1
  shared_preferences: ^2.3.3
  awesome_dialog: ^3.2.1
  rive: ^0.13.20
  jwt_decode: ^0.3.1
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  flutter_cached_pdfview: ^0.4.3
  percent_indicator: ^4.2.5
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  video_player: ^2.9.5
  better_player: ^0.0.84

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true

  # Add your assets here
  assets:
    - .env
    - assets/images/
    - assets/images/backgrounds/
    - assets/images/logo/
    - assets/images/menu_tab/
    - assets/images/flags/
    - assets/icons/facility_selection/
  # Add your custom fonts here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
  use_deferred_loading: false
